# 🚀 DEEPSEEK AI VALIDATION SUITE - MULTI-AGENT CONFIG
# The unfuckable AI validation orchestration config

# Agent definitions with API endpoints and capabilities
agents:
  deepseek:
    name: "DeepSeek Coder"
    type: "code_validation"
    endpoint: "https://api.deepseek.com/chat/completions"
    api_key_env: "DEEPSEEK_API_KEY"
    model: "deepseek-coder"
    cost_per_1k_tokens: 0.002
    tier_access: ["free", "basic", "professional", "enterprise", "white_label"]
    capabilities:
      - code_analysis
      - security_audit
      - performance_optimization
      - architecture_review
    max_tokens: 4000
    timeout: 30
    
  claude:
    name: "Claude 3.5 Sonnet"
    type: "advanced_reasoning"
    endpoint: "https://api.anthropic.com/v1/messages"
    api_key_env: "CLAUDE_API_KEY"
    model: "claude-3-5-sonnet-20241022"
    cost_per_1k_tokens: 0.003
    tier_access: ["basic", "professional", "enterprise", "white_label"]
    capabilities:
      - logical_analysis
      - edge_case_detection
      - consensus_building
      - technical_writing
    max_tokens: 4000
    timeout: 30
    
  gemini:
    name: "Gemini 2.0 Flash"
    type: "multimodal_analysis"
    endpoint: "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-exp:generateContent"
    api_key_env: "GEMINI_API_KEY"
    model: "gemini-2.0-flash-exp"
    cost_per_1k_tokens: 0.001
    tier_access: ["professional", "enterprise", "white_label"]
    capabilities:
      - pattern_recognition
      - visual_analysis
      - data_validation
      - multi_format_processing
    max_tokens: 4000
    timeout: 30
    
  grok:
    name: "Grok AI"
    type: "unrestricted_analysis"
    endpoint: "https://api.x.ai/v1/chat/completions"
    api_key_env: "GROK_API_KEY"
    model: "grok-beta"
    cost_per_1k_tokens: 0.002
    tier_access: ["enterprise", "white_label"]
    capabilities:
      - unrestricted_validation
      - controversial_content
      - edge_case_analysis
      - neutral_assessment
    max_tokens: 4000
    timeout: 30
    
  openai:
    name: "GPT-4 Turbo"
    type: "general_intelligence"
    endpoint: "https://api.openai.com/v1/chat/completions"
    api_key_env: "OPENAI_API_KEY"
    model: "gpt-4-turbo-preview"
    cost_per_1k_tokens: 0.01
    tier_access: ["professional", "enterprise", "white_label"]
    capabilities:
      - comprehensive_analysis
      - documentation_generation
      - test_case_creation
      - optimization_suggestions
    max_tokens: 4000
    timeout: 30

# Pre-configured validation chains for different use cases
validation_chains:
  free_basic:
    name: "Free Tier Validation"
    description: "Single-agent validation with DeepSeek"
    agents: ["deepseek"]
    consensus_threshold: 1.0
    max_cost: 0.10
    features:
      - basic_validation
      - syntax_checking
    
  pro_claude_deepseek:
    name: "Professional Dual Validation"
    description: "DeepSeek + Claude consensus validation"
    agents: ["deepseek", "claude"]
    consensus_threshold: 0.75
    max_cost: 0.50
    features:
      - advanced_validation
      - edge_case_detection
      - security_analysis
    
  enterprise_triple_check:
    name: "Enterprise Triple Validation"
    description: "DeepSeek + Claude + Gemini for maximum confidence"
    agents: ["deepseek", "claude", "gemini"]
    consensus_threshold: 0.67
    max_cost: 2.00
    features:
      - comprehensive_validation
      - multi_perspective_analysis
      - risk_assessment
      - compliance_checking
    
  unrestricted_validation:
    name: "Unrestricted Content Validation"
    description: "Grok + DeepSeek for content-neutral technical analysis"
    agents: ["grok", "deepseek"]
    consensus_threshold: 0.75
    max_cost: 1.00
    features:
      - unrestricted_analysis
      - technical_merit_only
      - no_moral_filtering
      - edge_case_handling
    
  luxury_fund_optimizer:
    name: "Luxury Car Fund Optimizer"
    description: "Multi-agent investment algorithm validation"
    agents: ["claude", "gemini", "deepseek"]
    consensus_threshold: 0.67
    max_cost: 3.00
    features:
      - investment_analysis
      - risk_modeling
      - performance_optimization
      - market_strategy_validation

# Subscription tiers and limits
subscription_tiers:
  free:
    name: "Free Tier"
    monthly_cost: 0
    validations_per_month: 100
    api_credit_budget: 5.00
    available_chains: ["free_basic"]
    features:
      - basic_validation
      - community_support
    rate_limit: 10  # per hour
    
  basic:
    name: "Basic Plan"
    monthly_cost: 29
    validations_per_month: 1000
    api_credit_budget: 25.00
    available_chains: ["free_basic", "pro_claude_deepseek"]
    features:
      - dual_agent_validation
      - email_support
      - basic_analytics
    rate_limit: 50  # per hour
    
  professional:
    name: "Professional Plan"
    monthly_cost: 99
    validations_per_month: 10000
    api_credit_budget: 150.00
    available_chains: ["free_basic", "pro_claude_deepseek", "enterprise_triple_check", "luxury_fund_optimizer"]
    features:
      - multi_agent_validation
      - priority_support
      - advanced_analytics
      - custom_chains
    rate_limit: 200  # per hour
    
  enterprise:
    name: "Enterprise Plan"
    monthly_cost: 499
    validations_per_month: -1  # unlimited
    api_credit_budget: 1000.00
    available_chains: ["*"]  # all chains
    features:
      - unlimited_validations
      - unrestricted_content
      - dedicated_support
      - custom_integrations
      - white_label_options
    rate_limit: 1000  # per hour
    
  white_label:
    name: "White Label License"
    monthly_cost: 2999
    validations_per_month: -1  # unlimited
    api_credit_budget: 5000.00
    available_chains: ["*"]  # all chains
    features:
      - full_customization
      - your_branding
      - dedicated_infrastructure
      - 24_7_support
      - revenue_sharing
    rate_limit: -1  # unlimited

# Cost management and optimization
cost_management:
  enable_caching: true
  cache_duration_hours: 24
  enable_fallback_agents: true
  auto_optimize_chains: true
  budget_alerts:
    - threshold: 0.8
      action: "warn"
    - threshold: 0.95
      action: "throttle"
    - threshold: 1.0
      action: "block"

# Revenue optimization settings
revenue_optimization:
  upsell_triggers:
    usage_limit_reached: true
    premium_feature_attempted: true
    high_engagement_detected: true
    trial_ending_soon: true
  
  dynamic_pricing:
    enable: true
    discount_max: 0.30
    promotional_periods:
      - name: "Launch Special"
        discount: 0.25
        end_date: "2025-12-31"
  
  affiliate_program:
    commission_rate: 0.20
    payment_method: "crypto"
    minimum_payout: 100

# Prompt templates for content-neutral validation
prompts:
  technical_validation:
    system: |
      You are a technical code validation specialist. Your job is to analyze code purely on technical merit:
      - Syntax correctness and logic flow
      - Security vulnerabilities and attack vectors
      - Performance bottlenecks and optimization opportunities
      - Architecture patterns and best practices
      - Edge cases and error handling
      
      You evaluate code functionality without moral judgment. Focus only on technical implementation quality.
    
  consensus_building:
    system: |
      You are participating in a multi-agent consensus validation. Review the other agents' assessments and provide:
      - Areas of agreement and disagreement
      - Technical evidence supporting your position
      - Compromise solutions that address all concerns
      - Final confidence score (0-1) for the validation
    
  edge_case_detection:
    system: |
      You specialize in finding edge cases and potential failures in code. Analyze for:
      - Input validation bypass opportunities
      - Race conditions and concurrency issues
      - Memory leaks and resource exhaustion
      - Boundary condition failures
      - Integration point vulnerabilities
      
      Report findings with technical specificity and suggested mitigations.

# API rate limiting and retry logic
api_settings:
  default_retry_attempts: 3
  retry_delay_seconds: 1
  exponential_backoff: true
  max_concurrent_requests: 10
  request_timeout_seconds: 30
  
# Monitoring and analytics
monitoring:
  enable_logging: true
  log_level: "INFO"
  metrics_collection: true
  performance_tracking: true
  error_reporting: true
  
# Security settings
security:
  api_key_rotation_days: 90
  audit_logging: true
  encryption_at_rest: true
  quantum_signature_validation: true